🐛 fix: update zend broken icon link
maurodesouza/profile-readme-generator pull request #82
Opened 2024-09-07 15:05 UTC by algovoid

## What type of PR is this? 

- [x] Bug Fix

## What I did

updated broken links .

2024-09-07 15:21 UTC, algovoid reviewed
fixed the linting issue

2024-09-21 19:44 UTC, algovoid commented
@maurodesouza

2024-09-23 03:01 UTC, maurodesouza requested changes

2024-09-23 03:01 UTC, maurodesouza commented on src/resources/tech_icons.ts
>          ],
The Laravel icons are still broken, and it seems to be due to the prefix codepen/. All other links follow the pattern brand/brand-icon.svg.

I believe it should be laravel/laravel-original.svg.

Could you please update this? Thanks!

2024-09-23 03:04 UTC, maurodesouza commented
Hi @algovoid 👋

Sorry for the late answer!

I reviewed your PR and found an issue with the Laravel icon links!

2024-09-23 13:22 UTC, algovoid reviewed
should work now .

2024-09-23 13:54 UTC, maurodesouza approved these changes

2024-09-23 13:54 UTC, merged